version: "4.24.1"
services:
  dev-postgres:
    image: postgres:16.0-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: hato
      POSTGRES_PASSWORD: hatotori
      POSTGRES_DB: hato
    restart: always
    networks:
      - lesson
networks:
  lesson: